"""Configuration loader for the karst_analysis pipeline.

Strategy
--------
- A canonical default config lives at ``config/pipeline_default.yml``
  and is shipped with the repo. It defines every key the pipeline can
  read. **Do not edit this file** — it is the frozen baseline.
- A user-editable config lives at ``config/pipeline.yml`` (or any
  other path given via ``--config``). The user config can be partial;
  missing keys fall back to the defaults via deep-merge.
- ``load_config(path)`` returns a fully-populated dict, validated
  against an internal schema. Any unknown key, missing required key,
  or type mismatch raises ``ConfigError`` with a clear message.

Why deep-merge
--------------
A user can override a single nested key without restating the entire
config. For example, a sensitivity-test config may contain just::

    preprocessing:
      savgol:
        window: 21

…and inherit everything else from the defaults. This makes
sensitivity sweeps cheap to write and easy to diff.

Design notes
------------
- The validator is **strict on type** but **permissive on missing keys**:
  if the user's YAML omits a key, we use the default. If a key has the
  wrong type (e.g. ``window: "eleven"``), we fail loudly.
- Unknown keys are warnings, not errors. This is intentional: the
  pipeline may add new keys, and we don't want old configs to break.
  The warning surfaces typos without aborting batches.
- The ``params_for_run_ledger`` helper extracts the subset relevant
  to a single run (e.g. just savgol params for a savgol run) so the
  ``runs.csv`` ledger entry is concise but traceable.
"""

from __future__ import annotations

import warnings
from copy import deepcopy
from pathlib import Path
from typing import Any, Optional

import yaml


# Path to the frozen baseline config — resolved relative to the project root.
_DEFAULT_CONFIG_NAME = "pipeline_default.yml"


class ConfigError(ValueError):
    """Raised on config loading / validation errors."""


# ──────────────────────────────────────────────────────────────────────
#  Schema (declarative)
#
#  Each leaf is a tuple (expected_type, allow_none). Compound nodes are
#  nested dicts. This is intentionally simple — we don't pull in
#  pydantic / cerberus / jsonschema. The schema lives next to the
#  defaults so adding a key requires editing two places (default value
#  and schema), which is easy to keep in sync.
# ──────────────────────────────────────────────────────────────────────

# Top-level config blocks that exist for visualization modules but
# whose internal keys are not validated centrally — those modules
# parse their own block directly via cfg["block_name"]. Listed here
# to suppress the "Unknown key" warning at the schema root level.
# If you add a NEW visualization block to pipeline_default.yml, also
# list its top-level key here.
_VIZ_BLOCKS_ALLOWLIST: frozenset[str] = frozenset({
    "sec_caliper_panel",   # v11
    "site_panel",          # v12
})

_SCHEMA: dict = {
    "campaign": (str, False),
    "preprocessing": {
        "methods": (list, False),
        "apply_depth_adjustment": (bool, False),
        "depth_adjustment": ((int, float), False),
        "depth_adjustment_method": (str, False),
        "apply_monotonic_descent_filter": (bool, False),
        "monotonic_descent_tolerance": ((int, float), False),
        "dz": ((int, float), True),                 # nullable
        "dz_method": (str, False),
        "apply_log10": (bool, False),
        "savgol": {
            "window": (int, False),
            "order": (int, False),
            "segmented": (bool, False),
            "gradient_factor": ((int, float), False),
            "min_gradient_threshold": ((int, float), False),
        },
        "lowess": {
            "frac": ((int, float), False),
            "degree": (int, False),
            "n_robust_iter": (int, False),
            "apply_pava": (bool, False),
        },
    },
    "breakpoints": {
        "max_breakpoints": (int, False),
        "n_trials": (int, False),
        "tolerance": ((int, float), False),
        "min_distance": ((int, float), False),
        "use_log10": (bool, False),
    },
    "robustness": {
        "delta_m": ((int, float), False),
        "sensitivity_deltas_m": (list, False),
        "n_min": (int, False),
        "n_max": (int, False),
        "smoothings": (list, False),
    },
    "convergence": {
        "sec_caliper": {
            # Input filtering
            "sec_agreement_min": (int, False),
            "caliper_severity_filter": (list, True),    # nullable
            # Matching rule
            "matching_rule": (str, False),
            "tolerance_m": ((int, float), False),
            # Best-match selection
            "best_match_priority": (str, False),
            # Scoring
            "severity_weights": (dict, False),
            # Unmatched-zones report
            "unmatched_zones_min_severity": (str, True), # nullable
            # Run tag (also used in filenames)
            "run_tag": (str, False),
        },
    },
    "ert": {
        "breakpoints": {
            "max_breakpoints": (int, False),
            "tolerance": ((int, float), False),
            "min_distance": ((int, float), False),
            "start_seed": (int, False),
            "max_seed_attempts": (int, False),
        },
        # PROVISIONAL placeholder, see pipeline_default.yml for context.
        "bot_mz_rho_threshold": ((int, float), False),
    },
}


# ──────────────────────────────────────────────────────────────────────
#  Domain-specific validation for the convergence.sec_caliper block.
#  Run AFTER schema validation, because we need the merged config.
# ──────────────────────────────────────────────────────────────────────
_VALID_MATCHING_RULES = {"overlap_only", "center_distance_only", "hybrid"}
_VALID_BEST_MATCH_PRIORITIES = {
    "overlap_then_distance",
    "max_severity",
    "max_peak_excess",
}
_VALID_SEVERITIES = {"mild", "moderate", "severe"}


def _validate_convergence_sec_caliper(cfg: dict) -> None:
    """Validate the convergence.sec_caliper sub-config against domain rules.

    Schema validation already checked types. This function checks that
    string values fall into known sets and that severity_weights has the
    right keys with numeric values. Raises ConfigError on any issue.
    """
    sub = cfg["convergence"]["sec_caliper"]

    rule = sub["matching_rule"]
    if rule not in _VALID_MATCHING_RULES:
        raise ConfigError(
            f"convergence.sec_caliper.matching_rule must be one of "
            f"{sorted(_VALID_MATCHING_RULES)}, got {rule!r}."
        )

    prio = sub["best_match_priority"]
    if prio not in _VALID_BEST_MATCH_PRIORITIES:
        raise ConfigError(
            f"convergence.sec_caliper.best_match_priority must be one of "
            f"{sorted(_VALID_BEST_MATCH_PRIORITIES)}, got {prio!r}."
        )

    sw = sub["severity_weights"]
    missing = _VALID_SEVERITIES - set(sw.keys())
    if missing:
        raise ConfigError(
            f"convergence.sec_caliper.severity_weights is missing keys: "
            f"{sorted(missing)}. Required keys: {sorted(_VALID_SEVERITIES)}."
        )
    extra = set(sw.keys()) - _VALID_SEVERITIES
    if extra:
        raise ConfigError(
            f"convergence.sec_caliper.severity_weights has unknown keys: "
            f"{sorted(extra)}. Allowed: {sorted(_VALID_SEVERITIES)}."
        )
    for sev, w in sw.items():
        if isinstance(w, bool) or not isinstance(w, (int, float)):
            raise ConfigError(
                f"convergence.sec_caliper.severity_weights[{sev!r}] must be "
                f"a number, got {type(w).__name__}."
            )

    tol = sub["tolerance_m"]
    if isinstance(tol, bool) or tol < 0:
        raise ConfigError(
            f"convergence.sec_caliper.tolerance_m must be >= 0, got {tol}."
        )

    amin = sub["sec_agreement_min"]
    if isinstance(amin, bool) or amin < 0:
        raise ConfigError(
            f"convergence.sec_caliper.sec_agreement_min must be >= 0, got {amin}."
        )

    sf = sub["caliper_severity_filter"]
    if sf is not None:
        bad = [s for s in sf if s not in _VALID_SEVERITIES]
        if bad:
            raise ConfigError(
                f"convergence.sec_caliper.caliper_severity_filter contains "
                f"unknown severities: {bad}. Allowed: {sorted(_VALID_SEVERITIES)}."
            )

    ums = sub["unmatched_zones_min_severity"]
    if ums is not None and ums not in _VALID_SEVERITIES:
        raise ConfigError(
            f"convergence.sec_caliper.unmatched_zones_min_severity must be "
            f"one of {sorted(_VALID_SEVERITIES)} or null, got {ums!r}."
        )


# ──────────────────────────────────────────────────────────────────────
#  Path resolution
# ──────────────────────────────────────────────────────────────────────
def _project_root() -> Path:
    """Return the project root (the dir containing pyproject.toml).

    Walks up from this file's location until pyproject.toml is found.
    Falls back to ``Path.cwd()`` if not found (unusual; e.g. running
    from a moved install).
    """
    here = Path(__file__).resolve()
    for parent in (here, *here.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    return Path.cwd()


def default_config_path() -> Path:
    """Path to the frozen baseline config that ships with the repo."""
    return _project_root() / "config" / _DEFAULT_CONFIG_NAME


# ──────────────────────────────────────────────────────────────────────
#  Loading
# ──────────────────────────────────────────────────────────────────────
def _load_yaml(path: Path) -> dict:
    """Read a YAML file. Returns ``{}`` if the file is empty or YAML-null."""
    if not path.exists():
        raise ConfigError(f"Config file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise ConfigError(
            f"Config file {path} must contain a YAML mapping at the top level, "
            f"got {type(data).__name__}."
        )
    return data


def _deep_merge(default: dict, override: dict) -> dict:
    """Recursively merge ``override`` into ``default``.

    Returns a new dict; does not mutate inputs. For each key:

    * If both values are dicts → recurse.
    * Otherwise → ``override`` wins (including for lists and None).
    """
    out = deepcopy(default)
    for k, v in override.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = deepcopy(v)
    return out


# ──────────────────────────────────────────────────────────────────────
#  Validation
# ──────────────────────────────────────────────────────────────────────
def _validate(node: dict, schema: dict, path: str = "") -> list[str]:
    """Walk the schema, validate types, return a list of warnings.

    Type mismatches and missing required keys raise ``ConfigError``
    immediately. Unknown keys are collected as warnings (returned).
    """
    warnings_out: list[str] = []

    # Required keys (everything in the schema is required, unless
    # "allow_none" → can be None but key must be present).
    for key, expected in schema.items():
        full = f"{path}.{key}" if path else key
        if key not in node:
            raise ConfigError(
                f"Missing required key '{full}'. "
                f"Default config should have it; merge logic is broken."
            )
        value = node[key]

        if isinstance(expected, dict):
            if not isinstance(value, dict):
                raise ConfigError(
                    f"Key '{full}' must be a mapping, got {type(value).__name__}."
                )
            warnings_out.extend(_validate(value, expected, full))
        else:
            expected_types, allow_none = expected
            if value is None:
                if not allow_none:
                    raise ConfigError(
                        f"Key '{full}' is null/None but a value is required."
                    )
                continue

            # Special: in Python, bool is a subclass of int. So
            # isinstance(True, int) is True. We need to short-circuit
            # this BEFORE the generic isinstance check, otherwise
            # ``window: true`` is accepted as int.
            int_or_number = (
                expected_types is int
                or expected_types == (int, float)
                or expected_types == (float, int)
            )
            if int_or_number and isinstance(value, bool):
                raise ConfigError(
                    f"Key '{full}' must be {'a number' if expected_types != int else 'int'}, "
                    f"got bool."
                )

            if not isinstance(value, expected_types):
                if expected_types is bool and not isinstance(value, bool):
                    raise ConfigError(
                        f"Key '{full}' must be bool, got {type(value).__name__}."
                    )
                if expected_types is str and not isinstance(value, str):
                    raise ConfigError(
                        f"Key '{full}' must be str, got {type(value).__name__}."
                    )
                if expected_types is list and not isinstance(value, list):
                    raise ConfigError(
                        f"Key '{full}' must be a list, got {type(value).__name__}."
                    )
                # Generic fallback
                names = (expected_types.__name__
                         if isinstance(expected_types, type)
                         else " or ".join(t.__name__ for t in expected_types))
                raise ConfigError(
                    f"Key '{full}' must be {names}, got {type(value).__name__}."
                )

    # Unknown keys — warn only, don't fail.
    # At the schema root level, suppress warnings for whitelisted
    # visualization blocks (which are parsed directly by their own
    # modules, not by this validator).
    for key in node:
        if key not in schema:
            if path == "" and key in _VIZ_BLOCKS_ALLOWLIST:
                continue
            full = f"{path}.{key}" if path else key
            warnings_out.append(
                f"Unknown key '{full}' (typo? schema-out-of-date?)"
            )

    return warnings_out


# ──────────────────────────────────────────────────────────────────────
#  Public API
# ──────────────────────────────────────────────────────────────────────
def load_config(
    path: Optional[Path | str] = None,
    *,
    default_path: Optional[Path | str] = None,
    warn_unknown: bool = True,
) -> dict:
    """Load a YAML config, merged with the canonical default.

    Parameters
    ----------
    path : path-like, optional
        Path to the user config. If None, loads only the default.
        Useful for tests and for scripts that want the canonical baseline.
    default_path : path-like, optional
        Override location of the default config (mainly for tests).
    warn_unknown : bool, default True
        If True, prints warnings for keys in the user config that
        don't appear in the schema.

    Returns
    -------
    dict
        Fully-populated, validated config dict.

    Raises
    ------
    ConfigError
        On missing files, invalid YAML, type errors, or missing
        required keys.
    """
    default_p = Path(default_path) if default_path is not None else default_config_path()
    default = _load_yaml(default_p)

    if path is not None:
        user = _load_yaml(Path(path))
        merged = _deep_merge(default, user)
    else:
        merged = default

    warns = _validate(merged, _SCHEMA)
    if warn_unknown:
        for w in warns:
            warnings.warn(f"[config] {w}", stacklevel=2)

    # Domain-specific validation that runs after schema validation.
    _validate_convergence_sec_caliper(merged)

    return merged


def params_for_run_ledger(config: dict, stage: str, method: Optional[str] = None) -> dict:
    """Extract the subset of config relevant to a single run.

    Used to populate the ``params_json`` field of ``results/runs.csv``
    in a way that is concise but traceable: only the parameters that
    actually affected this run are recorded.

    The flat keys returned for ``stage="preprocessing"`` are chosen to
    be compatible with ``runs.build_method_signature``, which expects
    short names like ``window``, ``order``, ``frac``, ``iter``,
    ``pava``, ``segmented``. Cleaning + log10 + method-specific
    sub-params come along too.

    Parameters
    ----------
    config : dict
        The fully-loaded config.
    stage : {"preprocessing", "breakpoints", "robustness"}
    method : str, optional
        For ``stage="preprocessing"``, one of ``"savgol"``, ``"lowess"``.
        Ignored for other stages.

    Returns
    -------
    dict
        Flat dict suitable for JSON serialisation in the ledger.
    """
    if stage == "preprocessing":
        if method is None:
            raise ValueError("method must be specified for preprocessing stage.")
        if method not in ("savgol", "lowess"):
            raise ValueError(f"Unknown method: {method}")
        pp = config["preprocessing"]
        out = {
            "method": method,
            "depth_adj": pp["depth_adjustment_method"] if pp["apply_depth_adjustment"] else None,
            "depth_adj_value": pp["depth_adjustment"] if pp["apply_depth_adjustment"] else None,
            "monotonic_descent": pp["apply_monotonic_descent_filter"],
            "log10": pp["apply_log10"],
        }
        # Method-specific parameters with the short names that
        # build_method_signature expects (window, order, segmented for
        # savgol; frac, iter, pava for lowess; plus extras).
        if method == "savgol":
            sp = pp["savgol"]
            out.update({
                "window": sp["window"],
                "order": sp["order"],
                "segmented": sp["segmented"],
                "gradient_factor": sp["gradient_factor"],
                "min_gradient_threshold": sp["min_gradient_threshold"],
            })
        else:  # lowess
            lp = pp["lowess"]
            out.update({
                "frac": lp["frac"],
                "degree": lp["degree"],
                "iter": lp["n_robust_iter"],
                "pava": lp["apply_pava"],
            })
        return out

    if stage == "breakpoints":
        return dict(config["breakpoints"])

    if stage == "robustness":
        return dict(config["robustness"])

    if stage == "convergence_sec_caliper":
        # Flatten the sub-config; it is already a flat dict of primitives
        # plus one nested dict (severity_weights).
        sub = dict(config["convergence"]["sec_caliper"])
        # Add the method key so build_method_signature has something to
        # work with via the generic fallback path.
        sub["method"] = "convergence_sec_caliper"
        return sub

    raise ValueError(f"Unknown stage: {stage}")
